### ISSUE TITLE
EODENT Error

### ISSUE THREAD

**Issue by Purethunder32** [packcord/discord-backup#1]
Hello there. It could just be my own incompetence, but whenever I try to install the package I get an EOENT error. I'd like to mention in advance I'm a novice with these types of things, but I have Node.js installed and I've installed and used some modules before. Thank you.

**Comment by Androz2091** [comment]
Hello
Can you send your error in full please?

**Comment by Purethunder32** [comment]
Sure thing, if you need any other information please let me know.

```0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'discord-backup'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.8.0
4 verbose npm-session 1133e0027584fb23
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/discord-backup 835ms (from cache)
8 silly pacote tag manifest for discord-backup@latest fetched in 1038ms
9 timing stage:loadCurrentTree Completed in 1295ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 37ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule discord-backup@1.0.4 checking installable status
17 silly fetchPackageMetaData error for discord.js@github:discordjs/discord.js#405bdb5b558eff478d0bde739cee1ee8e40c330b Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/discordjs/discord.js.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 http fetch GET 304 https://registry.npmjs.org/randomstring 162ms (from cache)
19 silly pacote range manifest for randomstring@^1.1.5 fetched in 202ms
20 silly resolveWithNewModule randomstring@1.1.5 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/fs 298ms (from cache)
22 silly pacote version manifest for fs@0.0.1-security fetched in 302ms
23 silly resolveWithNewModule fs@0.0.1-security checking installable status
24 timing stage:rollbackFailedOptional Completed in 1ms
25 timing stage:runTopLevelLifecycles Completed in 1737ms
26 silly saveTree system32
26 silly saveTree +-- async-limiter@1.0.1
26 silly saveTree +-- discord-backup@1.0.4
26 silly saveTree | +-- fs@0.0.1-security
26 silly saveTree | `-- randomstring@1.1.5
26 silly saveTree +-- discord.js@11.5.1
26 silly saveTree | +-- long@4.0.0
26 silly saveTree | +-- prism-media@0.0.3
26 silly saveTree | +-- snekfetch@3.6.4
26 silly saveTree | +-- tweetnacl@1.0.1
26 silly saveTree | `-- ws@6.2.1
26 silly saveTree +-- long@4.0.0
26 silly saveTree +-- prism-media@0.0.3
26 silly saveTree +-- snekfetch@3.6.4
26 silly saveTree +-- tweetnacl@1.0.1
26 silly saveTree `-- ws@6.2.1
27 verbose stack Error: spawn git ENOENT
27 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
27 verbose stack     at onErrorNT (internal/child_process.js:456:16)
27 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:77:11)
28 verbose cwd C:\WINDOWS\system32
29 verbose Windows_NT 10.0.17134
30 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "discord-backup"
31 verbose node v12.8.0
32 verbose npm  v6.10.2
33 error path git
34 error code ENOENT
35 error errno ENOENT
36 error syscall spawn git
37 error enoent Error while executing:
37 error enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/discord.js.git
37 error enoent
37 error enoent
37 error enoent spawn git ENOENT
38 error enoent This is related to npm not being able to find a file.
39 verbose exit [ 1, true ]
```

**Comment by Androz2091** [comment]
Are you sure that Git is installed? Retry to install the package in git bash 🤔

**Comment by Purethunder32** [comment]
That appears to have fixed it, thank you.

**Comment by Androz2091** [comment]
All right, fine. 👌
